const resource = {
    Message: {
        SaveDataSuccess: "Lưu dữ liệu thành công.",
        ApiErrorMsg: "Có lỗi xảy ra, vui lòng thử lại!",
        ConfirmCancelAddAsset: "Bạn có muốn huỷ bỏ khai báo tài sản này?",
        ConfirmCancelEditAsset:
            "Thông tin thay đổi sẽ không được cập nhật nếu bạn không lưu. Bạn có muốn lưu các thay dổi này?",
        ValidateDialogMsg: "Cần phải nhập thông tin ",
        ConfirmDeleteOne: "Bạn có muốn xoá tài sản ",
        ConfirmDeleteList:
            " tài sản đã được chọn. Bạn có muốn xoá các tài sản này khỏi danh sách? ",
        DeleteSuccess: "Xoá thành công.",
        UpdateDataSuccess: "Cập nhật dữ liệu thành công.",
        InValidDepreciationCost: "Giá trị hao mòn phải nhỏ hơn nguyên giá.",
        ErrorNotSelectDelete: "Vui lòng chọn bản ghi cần xoá",
        InValidUsedDate: "Ngày bắt đầu sử dụng phải lớn hơn ngày mua.",
        AssetNotEndChar: "Mã tài sản phải kết thúc bằng chữ số.",
        NotEmpty: " không được phép để trống",
        NeedInputInfo: "Cần phải nhập thông tin",
        ConfirmDeleteIncrease: "Bạn muốn xóa chứng từ có mã <b>",
        DuplicateSourceName: "Nguồn hình thành không được phép trùng!",
        ChooseLeastOneAsset: "Cần chọn ít nhất 1 tài sản",
        ConfirmDeleteListIncrease:
            " chứng từ đã được chọn. Bạn có muốn xoá các chứng từ này khỏi danh sách? ",
        ChooseDeleteIncreaseItem: "Cần chọn ít nhất 1 chứng từ!",
        ConfirmCancelEditIncrease:
            "Thông tin thay đổi sẽ không được cập nhật nếu bạn không lưu. Bạn có muốn lưu các thay dổi này?",
        ConfirmCancelAddIncrease: "Bạn muốn hủy bỏ khai báo chứng từ này?",
        ConfirmCancelNotEditIncrease: "Bạn muốn hủy bỏ sửa chứng từ này?",
    },
    TitleLabel: {
        Add: "Thêm tài sản",
        Edit: "Sửa tài sản",
        Duplicate: "Nhân bản tài sản",
        AddRecordIncrease: "Thêm chứng từ ghi tăng",
        ChooseAssetIncrease: "Chọn tài sản ghi tăng",
        EditAssetIncrease: "Sửa tài sản ",
        EditRecordIncrease: "Sửa chứng từ ghi tăng",
    },
    TitleInput: {
        Code: "Mã",
        AssetCode: "Mã tài sản",
        AssetName: "Tên tài sản",
        Department: "Bộ phận sử dụng",
        DepartmentCode: "Mã bộ phận sử dụng",
        DepartmentName: "Tên bộ phận sử dụng",
        AssetCategory: "Loại tài sản",
        AssetCategoryCode: "Mã loại tài sản",
        AssetCategoryName: "Tên loại tài sản",
        Quantity: "Số lượng",
        Cost: "Nguyên giá",
        LifeTime: "Thời gian sử dụng",
        TrackedYear: "Năm theo dõi",
        DepreciationRate: "Tỷ lệ hao mòn năm",
        DepreciationCost: "Giá trị hao mòn năm",
        PurchaseDate: "Ngày mua",
        UsedDate: "Ngày bắt đầu sử dụng",
    },
    TableHeader: {
        STT: "STT",
        AssetCode: "Mã tài sản",
        AssetName: "Tên tài sản",
        AssetCategory: "Loại tài sản",
        Department: "Bộ phận sử dụng",
        Quantity: "Số lượng",
        Cost: "Nguyên giá",
        AccumulatedDepreciation: "HM/KH luỹ kế",
        ResidualValue: "Giá trị còn lại",
        Function: "Chức năng",
    },
    Sidebar: {
        Overview: "Tổng quan",
        Asset: "Tài sản",
        RoadSystemAsset: "Tài sản HT-ĐB",
        Tools: "Công cụ dụng cụ",
        Category: "Danh mục",
        Search: "Tra cứu",
        Report: "Báo cáo",
    },
    Tooltips: {
        AccumulatedDepreciation: "Hao mòn hoặc khấu hao luỹ kế",
        SaveHotKey: "Lưu (Ctrl + S)",
        CloseHotKey: "Đóng (Esc)",
        RoadSystemAsset: "Tài sản hạ tầng đường bộ",
        ExportExcel: "Xuất file Excel",
        DeleteRecords: "Xoá bản ghi",
        FullScreen: "Toàn màn hình",
        UnFullScreen: "Thu gọn",
        Edit: "Chỉnh sửa",
        Delete: "Xoá",
        Duplicate: "Nhân bản",
        Add: "Thêm",
        ExportExcel: "Xuất file Excel",
        DeleteRecord: "Xoá bản ghi",
        NextPage: "Trang sau",
        PrevPage: "Trang trước",
    },
    Button: {
        AddAsset: "Thêm tài sản",
        Save: "Lưu",
        DontSave: "Không lưu",
        Cancel: "Huỷ",
        Delete: "Xoá",
        No: "Không",
        Close: "Đóng",
    },
    Link: {
        Overview: "/tong-quan",
        Asset: "/tai-san",
        RoadSystemAsset: "/tai-san-ht-db",
        Tools: "/cong-cu",
        Category: "/danh-muc",
        Search: "/tra-cuu",
        Report: "/bao-cao",
        Login: "/dang-nhap",
        Register: "/dang-ky",
    },
    Source: {
        Center: "Ngân sách trung ương",
        Province: "Ngân sách tỉnh",
        District: "Ngân sách huyện",
        Commune: "Ngân sách xã",
    },
    TypeForm: {
        Add: "add",
        Edit: "edit",
        Duplicate: "duplicate",
    },
    TypeDialog: {
        Add: "add",
        Edit: "edit",
        Duplicate: "duplicate",
        Error: "error",
        Delete: "delete",
    },
};

export default resource;
